# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do
# not exceed four million, find the sum of the even-valued terms.

current = 2
prev = 1

tot = 2
exceeds = True
#4000000
number = 100
while (exceeds):
	temp = prev
	prev = current
	print (float(current)/float(temp))
	current = temp + current
	print "Current current is", current
	if ((current < 4000000) and (current%2 == 0)):
		tot += current
		print "added tot"
	if (current > 4000000):
		exceeds = False;
		print "Current exceeded", current

print tot



